version: "2.4"
services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        links:
            - db

    db:
        image: "postgres:9.6"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: hunter2
    django:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./django:/opt/app
        command: tail -f /dev/null
        env_file:
            - .venv