# Generated by Django 4.1.7 on 2023-03-09 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='descrription',
            new_name='description',
        ),
    ]
