# Generated by Django 4.1.7 on 2023-03-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
