# Generated by Django 4.1.7 on 2023-03-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('1', 'Not Done'), ('2', 'Doing'), ('3', 'Done')], default='1', max_length=20),
        ),
    ]
