# Generated by Django 4.1.7 on 2023-03-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_log_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='todo',
        ),
        migrations.AddField(
            model_name='log',
            name='name_log',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
